name: Weekly Bugzilla Report

on:
  schedule:
    - cron: '0 8 * * 1'  # Every Monday at 08:00 UTC
  workflow_dispatch:     # Allows manual run from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Weekly Bugzilla Report
        run: python weekly_bugzilla_report.py

      - name: Upload report image
      - uses: actions/upload-artifact@v4
        with:
          name: bugzilla-report
          path: weekly_reports/
